[project]
name = "drips-multiplex-relations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "drips-complex",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]

[tool.uv.sources]
drips-complex = { path = "../drips_complex", editable = true }

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
